apiVersion: apps/v1
kind: Deployment
metadata:
  name: stringsvc-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stringsvc-service
  template:
    metadata:
      labels:
        app: stringsvc-service
    spec:
      containers:
        - name: stringsvc-service
          image: fnaumov/stringsvc:latest
          imagePullPolicy: Never # for production need to set "Always"
          ports:
            - containerPort: 8080
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: stringsvc-service
spec:
  selector:
    app: stringsvc-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 8081
      targetPort: 8081
  type: NodePort
